//
//  RegisterPresenter.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterPresenter: RegisterPresenterProtocol {
    
    weak private var view: RegisterViewProtocol?
    var interactor: RegisterInteractorProtocol?
    private let router: RegisterWireframeProtocol
    
    init(interface: RegisterViewProtocol, interactor: RegisterInteractorProtocol?, router: RegisterWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func obtenerDatosUsuario(item: UsuarioDatos) {
        interactor?.datosUsuario(usuarioDatos: item)
    }
    
    func createdDataUser() {
        view?.actualizarDatosUsuarios()
    }
    
    func didError(error: String) {
        view?.didError(error: error)
    }
}
