//
//  RegisterInteractor.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseFirestore
import FirebaseAuth

class RegisterInteractor: RegisterInteractorProtocol {
    
    weak var presenter: RegisterPresenterProtocol?
    let db = Firestore.firestore()
    
    func dataUser(usuarioDatos: UsuarioDatos){
        
        let dict = ["nombre": usuarioDatos.nombre ,
                    "apellido": usuarioDatos.apellido,
                    "correoElectronico": usuarioDatos.correo ]
        db.collection("users").addDocument(data: dict)
    }
    
    func datosUsuario(usuarioDatos: UsuarioDatos) {
        
        let email = usuarioDatos.correo
        let password = usuarioDatos.contraseña
        
        Auth.auth().createUser(withEmail: email, password: password) {
            (result, error) in
            if let result = result, error == nil{
                
                self.dataUser(usuarioDatos: usuarioDatos)
                self.presenter?.createdDataUser()
            }else{
                self.presenter?.didError(error: error!.localizedDescription)
            }
        }
    }
}
