//
//  SingInInteractor.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseAuth

class SingInInteractor: SingInInteractorProtocol {
    
    weak var presenter: SingInPresenterProtocol?
    
    
    func datosUsuarioEmail(email: String, password: String) {
        
        Auth.auth().signIn(withEmail: email, password: password) {
            (result, error) in
            if let result = result, error == nil {
                self.presenter?.recuperarDatos(isSucces: true)
            }else {
                self.presenter?.recuperarDatos(isSucces: false)
            }
        }
    }
}

