//
//  SingInProtocols.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SingInWireframeProtocol: class {

}
//MARK: Presenter -
protocol SingInPresenterProtocol: class {
    func datosUsuarioEmail(email: String , password: String)
    func recuperarDatos(isSucces: Bool) 

}

//MARK: Interactor -
protocol SingInInteractorProtocol: class {

  var presenter: SingInPresenterProtocol?  { get set }

    func datosUsuarioEmail(email: String, password: String)


}

//MARK: View -
protocol SingInViewProtocol: class {

  var presenter: SingInPresenterProtocol?  { get set }

    func actualizarDatosUsuariosEmail(isSucces: Bool)
}
