//
//  menuViewController.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class menuViewController: UIViewController, menuViewProtocol {

    @IBOutlet weak var btnInicia: UIButton!

	var presenter: menuPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        btnInicia.layer.cornerRadius = 18
    }

    @IBAction func btnActionInicio(_ sender: Any) {

        let myViewController = SingInRouter.createModule()
        myViewController.modalPresentationStyle = .fullScreen
        self.present(myViewController, animated: true, completion: nil)

    }

}
