//
//  menuInteractor.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class menuInteractor: menuInteractorProtocol {

    weak var presenter: menuPresenterProtocol?
}
