//
//  menuProtocols.swift
//  Pruebabambu
//
//  Created luis hector hernandez godinez  on 12/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol menuWireframeProtocol: class {

}
//MARK: Presenter -
protocol menuPresenterProtocol: class {

}

//MARK: Interactor -
protocol menuInteractorProtocol: class {

  var presenter: menuPresenterProtocol?  { get set }
}

//MARK: View -
protocol menuViewProtocol: class {

  var presenter: menuPresenterProtocol?  { get set }
}
